### ISSUE TITLE
Prevent same user counting multiple times in a row

### ISSUE THREAD

**Issue by GamEsnitzhel** [The-Mist-Development/The-Mist-Bot#13]
One user can literally just count forever lol.

**Comment by R2D2VaderBeef** [comment]
We planned to fix this in time for v2 but never did 😔

Possible ways to fix: Stored the last counted user ID in the database and check it against every count.

**Comment by kamicavi** [comment]
Huh, I fixed this in the original counting redesign, but I never rebased it for v2.

**Comment by R2D2VaderBeef** [comment]
I've thought of a good way to test (stolen from DiscordSRV): I'll make a dev branch which we'll keep updated with Master, and then all PRs can be merged there for testing.

**Comment by R2D2VaderBeef** [comment]
I fixed this in commit [310c7c8](https://github.com/The-Mist-Development/The-Mist-Bot/commit/310c7c8d42cbe8a693e2d223b9bf9c1c0afe6491).
